import type { RoleFamily } from "@/lib/niche";

export type Domain = "overheid" | "finance" | "zorg" | "logistiek" | "energie" | "tech";

export type BenchPerson = {
  id: string;
  name: string;
  title: string;
  family: RoleFamily;
  city: string;
  rate: number;
  available: "nu" | "2w" | "1m";
  zzpYears: number;
  stack: string[];
  domains: Domain[];
  last: string;
  highlights: string[];
};

/**
 * Vervangbare bench — dit is wat een licentienemer inwisselt voor eigen CRM.
 * Fictieve namen, echte NL contracting-patronen.
 */
export const BENCH: BenchPerson[] = [
  {
    id: "ba-joost",
    name: "Joost van Dijk",
    title: "Senior Business Analist",
    family: "ba-pm",
    city: "Eindhoven",
    rate: 88,
    available: "nu",
    zzpYears: 8,
    stack: ["BPMN", "Archimate", "Jira", "SQL", "Azure DevOps", "XR"],
    domains: ["overheid", "logistiek"],
    last: "IV-keten Politie · processen & requirements",
    highlights: [
      "Publieke keten: van intake tot opleidingsadministratie",
      "Vertalen van wet- en regelgeving naar user stories",
    ],
  },
  {
    id: "ba-samira",
    name: "Samira El Amrani",
    title: "Business Analist / PO",
    family: "ba-pm",
    city: "Utrecht",
    rate: 92,
    available: "2w",
    zzpYears: 6,
    stack: ["SAFe", "Jira", "Confluence", "SQL", "Power BI"],
    domains: ["finance", "overheid"],
    last: "NN · BA op klantreis + data-rapportages",
    highlights: [
      "Brug tussen business en IT in gereguleerde orgs",
      "Sterk in stakeholder-management zonder drama",
    ],
  },
  {
    id: "ba-esmee",
    name: "Esmée Bakker",
    title: "Business Analist data/IV",
    family: "ba-pm",
    city: "Den Haag",
    rate: 90,
    available: "nu",
    zzpYears: 5,
    stack: ["SQL", "BPMN", "Sparx", "ServiceNow"],
    domains: ["overheid", "zorg"],
    last: "Gemeente · zaaksysteem & IV-architectuur",
    highlights: [
      "Overheid-IV: zaakgericht werken, AVG, GIBIT",
      "Kan met architecten én met de lijn praten",
    ],
  },
  {
    id: "pm-thomas",
    name: "Thomas de Groot",
    title: "Interim Project Manager",
    family: "ba-pm",
    city: "Amsterdam",
    rate: 105,
    available: "1m",
    zzpYears: 11,
    stack: ["PRINCE2", "SAFe", "MS Project", "Jira"],
    domains: ["finance", "tech"],
    last: "ING · payments-migratie",
    highlights: ["Stuurt mixed perm/ZZP-teams", "Strakke governance, weinig slides"],
  },
  {
    id: "sm-lina",
    name: "Lina Bergström",
    title: "Scrum Master",
    family: "agile",
    city: "Amsterdam",
    rate: 95,
    available: "nu",
    zzpYears: 7,
    stack: ["SAFe", "Kanban", "Jira", "Miro"],
    domains: ["tech", "finance"],
    last: "Adyen · platform squad",
    highlights: ["Delivery in high-compliance fintech", "Geen agile-theater"],
  },
  {
    id: "sm-daan",
    name: "Daan Visser",
    title: "Scrum Master / Agile Coach",
    family: "agile",
    city: "Rotterdam",
    rate: 98,
    available: "2w",
    zzpYears: 9,
    stack: ["SAFe", "LeSS", "Facilitatie", "Jira"],
    domains: ["overheid", "logistiek"],
    last: "Havenbedrijf · tribe-coaching",
    highlights: ["Publieke orgs die ‘agile moeten’", "Werkt met weerstand, niet ertegen"],
  },
  {
    id: "ac-mirjam",
    name: "Mirjam Holt",
    title: "Agile Coach",
    family: "agile",
    city: "Haarlem",
    rate: 110,
    available: "1m",
    zzpYears: 12,
    stack: ["SAFe", "Team Topologies", "Coaching"],
    domains: ["finance", "overheid"],
    last: "Rabobank · chapter agile",
    highlights: ["Schaal-agile zonder extra lagen", "Coach van managers, niet van post-its"],
  },
  {
    id: "dev-karim",
    name: "Karim Haddad",
    title: "DevOps / Platform Engineer",
    family: "cloud-devops",
    city: "Amsterdam",
    rate: 112,
    available: "nu",
    zzpYears: 6,
    stack: ["Kubernetes", "Terraform", "AWS", "GitHub Actions", "Python"],
    domains: ["tech", "finance"],
    last: "Mollie · platform reliability",
    highlights: ["CI/CD en platform-pijn in scale-ups", "Praat business én YAML"],
  },
  {
    id: "dev-noor",
    name: "Noor Janssen",
    title: "Azure DevOps Engineer",
    family: "cloud-devops",
    city: "Eindhoven",
    rate: 108,
    available: "2w",
    zzpYears: 5,
    stack: ["Azure", "Terraform", "AKS", "YAML", "PowerShell"],
    domains: ["overheid", "energie"],
    last: "Alliander · cloud landing zone",
    highlights: ["Azure in semipublieke context", "BIO/NIS2-bewust"],
  },
  {
    id: "dev-stijn",
    name: "Stijn Kuipers",
    title: "Cloud Engineer",
    family: "cloud-devops",
    city: "Utrecht",
    rate: 115,
    available: "1m",
    zzpYears: 8,
    stack: ["GCP", "AWS", "Terraform", "Go", "Kubernetes"],
    domains: ["tech", "logistiek"],
    last: "Coolblue · cost + platform",
    highlights: ["Schaal + cost control", "Geen greenfield-romantiek"],
  },
  {
    id: "sw-femke",
    name: "Femke de Wit",
    title: "Java / Kotlin Engineer",
    family: "software",
    city: "Utrecht",
    rate: 102,
    available: "nu",
    zzpYears: 7,
    stack: ["Java", "Kotlin", "Spring", "Kafka", "PostgreSQL"],
    domains: ["finance", "overheid"],
    last: "Belastingdienst-keten · event-driven",
    highlights: ["Backends die 10 jaar moeten meegaan", "Kafka zonder circus"],
  },
  {
    id: "sw-omar",
    name: "Omar Saleh",
    title: "Node.js / TypeScript",
    family: "software",
    city: "Amsterdam",
    rate: 100,
    available: "2w",
    zzpYears: 5,
    stack: ["Node.js", "TypeScript", "NestJS", "Postgres", "React"],
    domains: ["tech", "finance"],
    last: "Bunq · onboarding APIs",
    highlights: ["Snelle delivery, nette contracts", "Full-stack als het moet"],
  },
  {
    id: "sw-lisa",
    name: "Lisa Hartog",
    title: ".NET Engineer",
    family: "software",
    city: "Arnhem",
    rate: 98,
    available: "nu",
    zzpYears: 9,
    stack: [".NET", "C#", "Azure", "SQL Server", "Blazor"],
    domains: ["overheid", "zorg"],
    last: "GGD · zaaksysteem-koppelingen",
    highlights: ["Microsoft-stack in de publieke sector", "Integraties boven features"],
  },
  {
    id: "data-yara",
    name: "Yara Meijer",
    title: "Data Engineer",
    family: "data",
    city: "Amsterdam",
    rate: 108,
    available: "nu",
    zzpYears: 4,
    stack: ["dbt", "Snowflake", "Python", "Airflow", "SQL"],
    domains: ["finance", "tech"],
    last: "Adyen · analytics platform",
    highlights: ["Van raw events naar betrouwbare marts", "Houdt van saaie pipelines"],
  },
  {
    id: "data-bram",
    name: "Bram Hofman",
    title: "Data Engineer / Analytics",
    family: "data",
    city: "Den Bosch",
    rate: 96,
    available: "2w",
    zzpYears: 6,
    stack: ["SQL", "Power BI", "Python", "Azure Data Factory"],
    domains: ["overheid", "energie"],
    last: "Waterschap · stuurinformatie",
    highlights: ["Data voor beleidsmakers, geen hobby-modellen", "Azure-native"],
  },
  {
    id: "ux-iris",
    name: "Iris Vermeer",
    title: "Product Designer / UX",
    family: "frontend-design",
    city: "Rotterdam",
    rate: 94,
    available: "nu",
    zzpYears: 8,
    stack: ["Figma", "Research", "Design systems", "WCAG"],
    domains: ["overheid", "zorg"],
    last: "DUO · aanvraagflows",
    highlights: ["Toegankelijkheid is default", "Research voordat er geschoven wordt"],
  },
  {
    id: "fe-niels",
    name: "Niels Bakker",
    title: "Frontend Engineer",
    family: "frontend-design",
    city: "Amsterdam",
    rate: 102,
    available: "2w",
    zzpYears: 6,
    stack: ["React", "TypeScript", "Next.js", "Accessibility"],
    domains: ["tech", "finance"],
    last: "Mollie · merchant dashboard",
    highlights: ["Design-system-first", "Geen JS-voor-JS"],
  },
  {
    id: "sec-anouk",
    name: "Anouk Veldman",
    title: "Security / BISO",
    family: "security",
    city: "Den Haag",
    rate: 118,
    available: "1m",
    zzpYears: 10,
    stack: ["ISO 27001", "BIO", "NIS2", "IAM", "Risk"],
    domains: ["overheid", "finance"],
    last: "Ministerie · BISO-rol",
    highlights: ["Vertaalt control frameworks naar doen", "Geen audit-theater"],
  },
  {
    id: "sec-jeroen",
    name: "Jeroen Smit",
    title: "Security Engineer",
    family: "security",
    city: "Utrecht",
    rate: 114,
    available: "nu",
    zzpYears: 7,
    stack: ["IAM", "Azure AD", "SIEM", "Terraform"],
    domains: ["tech", "overheid"],
    last: "KPN · identity platform",
    highlights: ["IAM op schaal", "Engineer, geen alleen-policy"],
  },
  {
    id: "test-kim",
    name: "Kim de Boer",
    title: "Test Lead",
    family: "test",
    city: "Amersfoort",
    rate: 90,
    available: "nu",
    zzpYears: 9,
    stack: ["TMap", "Cypress", "Playwright", "Azure DevOps"],
    domains: ["overheid", "finance"],
    last: "UWV · regressie & keten",
    highlights: ["Keten-testen in logge landschappen", "Test als poort, niet als extra sprint"],
  },
  {
    id: "test-pieter",
    name: "Pieter Wolters",
    title: "QA Engineer",
    family: "test",
    city: "Maastricht",
    rate: 86,
    available: "2w",
    zzpYears: 4,
    stack: ["Playwright", "API testing", "Java", "CI"],
    domains: ["tech", "logistiek"],
    last: "Bol.com · testautomatisering",
    highlights: ["Automation die blijft lopen", "Geen 2000 flaky tests"],
  },
  {
    id: "arch-helen",
    name: "Helen Prins",
    title: "Solution Architect",
    family: "architecture-apps",
    city: "Utrecht",
    rate: 125,
    available: "2w",
    zzpYears: 14,
    stack: ["Archimate", "Azure", "Integratie", "TOGAF"],
    domains: ["overheid", "finance"],
    last: "Achmea · target architecture",
    highlights: ["Beslissingen op papier die teams kunnen bouwen", "Integreert, dicteert niet"],
  },
  {
    id: "arch-marc",
    name: "Marc Nguyen",
    title: "Enterprise Architect",
    family: "architecture-apps",
    city: "Den Haag",
    rate: 130,
    available: "1m",
    zzpYears: 16,
    stack: ["Archimate", "NORA", "Cloud", "Security"],
    domains: ["overheid"],
    last: "Rijk · generieke voorzieningen",
    highlights: ["NORA/GEMMA-landschap", "Politiek-bestuurlijk schakelen"],
  },
];
