/* Regie mock data — Adyen case + RPS demand signals */
window.REGIE = {
  mode: "delivery", // delivery | demand

  opdracht: {
    id: "OPP-ADYEN-2026-017",
    titel: "Infrastructure (Cloud) Engineer",
    klant: "Adyen",
    locatie: "Amsterdam · office-first / hybrid",
    start: "ASAP · bij voorkeur sept 2026",
    tarief: "€110–125 / uur (indicatie)",
    duur: "6 maanden + verlenging",
    mustHaves: [
      "Linux at scale",
      "AWS / Azure / GCP",
      "Terraform of Pulumi",
      "Netwerk / IAM / hybrid connectivity",
      "Automation (Bash/Python/Go)",
    ],
    niceToHaves: ["Observability", "Cost controls", "On-prem + cloud", "Payments/fintech"],
    boolean:
      '("Infrastructure Engineer" OR "Cloud Engineer" OR SRE) AND (AWS OR GCP OR Azure) AND (Terraform OR Pulumi) AND Linux AND (Amsterdam OR Netherlands)',
    schaarste: "Zeer hoog",
    marktTarief: "€105–128",
    bron: "LinkedIn RPS + hiring post (Victor Camargo / Adyen Infra)",
    employmentPosted: "Full-time (perm)",
    contractingAngle:
      "Perm-vacature, maar urgente infra-capaciteit → soft signal voor interim/contracting-gesprek met hiring manager.",
    rpsProject: "RPS · Adyen Infra Cloud · reactive op HM-behoefte",
    story:
      "Adyen zoekt Cloud Infra (posting = vast). Brand New Start pitcht interim parallel: sneller capaciteit terwijl FTE-werving doorloopt.",
    leadKandidaat: "K-501",
    leadWhy:
      "Samira scoort 91% op must-haves, beschikbaar 1 sep, ZZP/BV oké, tarief in band — daarom is zij de lead in dit traject (Marc & Priya zijn backup).",
  },

  kandidaten: [
    {
      id: "K-501",
      naam: "Samira El Amrani",
      titel: "Cloud Infrastructure Engineer",
      score: 91,
      tarief: 118,
      beschikbaar: "1 sep",
      bron: "LinkedIn RPS",
      sterke: ["Linux at scale", "AWS networking", "Terraform", "Hybrid connectivity"],
      risico: "Geen Adyen/payments-ervaring; wel regulated fintech",
      waaromLead:
        "Beste match op must-haves + start 1 sep + tarief €118 in band. Agents zetten haar voor; jij keurt of zij de lead blijft.",
      vragen: [
        "Beschrijf een hybrid connectivity-setup die je hebt gebouwd (VPN/Direct Connect + IAM).",
        "Hoe automatiseer je multi-cloud foundations met Terraform of Pulumi?",
        "Hoe ga je om met cost controls en observability op productie-infra?",
      ],
    },
    {
      id: "K-502",
      naam: "Marc de Vries",
      titel: "Senior Platform / Infra",
      score: 86,
      tarief: 122,
      beschikbaar: "15 sep",
      bron: "GitHub + RPS",
      sterke: ["GCP", "Pulumi", "Linux", "On-call"],
      risico: "Tarief boven indicatieband",
      waaromLead: "Backup — sterke GCP, later beschikbaar, tarief iets hoog.",
      vragen: [],
    },
    {
      id: "K-503",
      naam: "Priya Nair",
      titel: "SRE · Cloud Foundations",
      score: 82,
      tarief: 112,
      beschikbaar: "direct",
      bron: "ATS",
      sterke: ["AWS", "Ansible", "Observability", "IAM"],
      risico: "Minder diepte in complex network topologies",
      waaromLead: "Backup — sneller beschikbaar, netwerk-diepte iets lager.",
      vragen: [],
    },
  ],

  screeningChat: [
    { from: "agent", text: "Hoi Samira — Adyen zoekt (mogelijk interim) versterking op Infrastructure Cloud in Amsterdam. 5 snelle checks?" },
    { from: "kandidaat", text: "Ja, prima." },
    { from: "agent", text: "Ben je beschikbaar vanaf begin september?" },
    { from: "kandidaat", text: "1 september werkt. Huidige klus eindigt 29 aug." },
    { from: "agent", text: "Wat is je uurtarief?" },
    { from: "kandidaat", text: "€118 excl. btw." },
    { from: "agent", text: "Werk je als ZZP'er / via BV?" },
    { from: "kandidaat", text: "Ja, BV + goedgekeurde modelovereenkomst." },
    { from: "agent", text: "Hands-on met Terraform én hybrid cloud networking (IAM, connectivity)?" },
    { from: "kandidaat", text: "Ja — o.a. AWS + on-prem interconnect bij een bank." },
    { from: "agent", text: "Office-first Amsterdam: hoeveel dagen op locatie?" },
    { from: "kandidaat", text: "3–4 dagen/week is oké voor een Adyen-klus." },
    { from: "agent", text: "Top — shortlist. Recruiter pakt het hiring-manager gesprek op." },
  ],

  voorstel: {
    aan: "infra-hiring@adyen.com",
    onderwerp: "Interim voorstel: Samira El Amrani — Infrastructure (Cloud) Engineer",
    body: `Beste team,

Naar aanleiding van jullie Infrastructure (Cloud) Engineer-behoefte in Amsterdam stel ik Samira El Amrani voor — als sterke interim-optie naast (of in afwachting van) permanente hiring.

Samira heeft 8+ jaar Linux/cloud foundations, diepte in AWS networking & IAM, Terraform, en hybrid connectivity. Recent bouwde zij cloud foundations + interconnect bij een regulated fintech.

Beschikbaar: 1 september
Tarief: €118 / uur
Inzet: 3–4 dagen Amsterdam office-first

Ik realiseer me dat de posting full-time is; als jullie capaciteit eerder nodig hebben, kan interim de time-to-capacity verkorten terwijl permanente werving doorloopt.

CV en profiel in de bijlage. Kennismaking inplannen?

Met vriendelijke groet,
Kevin · Regie`,
  },

  planning: [
    { dag: "di 12 aug", slot: "10:00–10:45", met: "Cloud Eng. hiring manager", status: "voorgesteld" },
    { dag: "wo 13 aug", slot: "14:30–15:15", met: "Infra tech lead", status: "geboekt" },
    { dag: "do 14 aug", slot: "09:00–09:45", met: "Platform architect", status: "wacht" },
  ],

  followUps: [
    { wie: "Marc de Vries", wanneer: "over 3 dagen", actie: "Tarief / Adyen-interesse" },
    { wie: "Priya Nair", wanneer: "over 1 week", actie: "AWS networking depth-check" },
    { wie: "Pool · Cloud Infra AMS", wanneer: "wekelijks", actie: "Warmtecheck 24 kandidaten" },
  ],

  admin: [
    { item: "Overeenkomst van opdracht", status: "klaar" },
    { item: "DBA / modelovereenkomst", status: "check" },
    { item: "Adyen supplier / security onboarding", status: "pending" },
    { item: "Urenregistratie template", status: "klaar" },
    { item: "Verlenging reminder (T-30)", status: "klaar" },
  ],

  humanLane: [
    { id: "h1", label: "Vertrouwen Adyen HM", note: "Interim naast perm pitchen", done: false },
    { id: "h2", label: "Tariefonderhandeling", note: "", done: false },
    { id: "h3", label: "Soft skills & teamfit", note: "Office-first cultuur", done: false },
    { id: "h4", label: "Schaarse kandidaat overtuigen", note: "Samira · Adyen brand", done: false },
    { id: "h5", label: "Commerciële acquisitie", note: "Demand-tak · RPS BD", done: false },
  ],

  /* —— Demand / RPS zijtak —— */
  demand: {
    headline: "Client demand · RPS-gedreven",
    sub: "Twee lussen: (1) kandidaten vertellen waar interviews nú lopen, (2) gefilterde jobs → persoonlijke HM-outreach om contractors aan te bieden.",
    rpsNote:
      "LinkedIn RPS = Recruiter Professional Services (agency). RPS+ voegt Business Development mode toe om bedrijven te vinden die actief hiring zijn. Er is geen vrije ‘dump’ van RPS-data naar tools — koppeling via export, ATS-sync, Talent Insights, of handmatige project-watch.",

    alerts: [
      {
        type: "hot",
        text: "Adyen: 2 kandidaten melden deze week een gesprek daar — signaal bevestigd",
        when: "vandaag",
      },
      {
        type: "new",
        text: "Mollie: vacature staat als Contract (ZZP/interim) — niet alleen vast",
        when: "vandaag",
      },
      {
        type: "action",
        text: "Bunq: 9 dagen geen contact meer na hun interim-signaal — bericht naar hiring manager staat klaar",
        when: "nu",
      },
    ],

    radar: [
      {
        id: "r1",
        company: "Adyen",
        hm: "Victor Camargo",
        hmRole: "Cloud Engineer · hiring post",
        role: "Infrastructure (Cloud) Engineer",
        roleType: "extern mogelijk",
        employmentPosted: "Full-time",
        lastTalk: "2026-08-05",
        lastTalkLabel: "gisteren",
        talks: [
          { when: "5 aug", what: "2e gesprek tech lead", via: "Samira (screening)" },
          { when: "4 aug", what: "Recruiter screen Observability", via: "Priya (pulse)" },
        ],
        signalStrength: 92,
        trend: "up",
        contractReady: false,
        sources: ["pulse", "hm-post"],
        kansFactors: [
          { label: "2 kandidaten melden gesprek deze week", points: 35, source: "pulse" },
          { label: "Gesprek was gisteren (zeer recent)", points: 25, source: "pulse" },
          { label: "Hiring manager post actief (capacity)", points: 20, source: "hm-post" },
          { label: "Schaarse cloud/infra skills", points: 12, source: null },
        ],
        nextOptions: [
          {
            id: "interim-pitch",
            label: "Interim parallel pitchen",
            desc: "Hiring manager benaderen: contractor naast vaste werving",
          },
          {
            id: "shortlist",
            label: "Shortlist klaarzetten",
            desc: "2–3 pre-screened profielen klaarzetten",
          },
          {
            id: "watch",
            label: "Alleen monitoren",
            desc: "Nog geen outreach — wachten op sterker ZZP-signaal",
          },
        ],
        suggestedNext: "interim-pitch",
        suggestedWho: "agent",
        status: "hot",
      },
      {
        id: "r2",
        company: "Mollie",
        hm: "Platform hiring manager",
        hmRole: "via job posting",
        role: "Platform Engineer",
        roleType: "contract",
        employmentPosted: "Contract",
        lastTalk: "2026-08-03",
        lastTalkLabel: "3 dagen geleden",
        talks: [
          { when: "3 aug", what: "Take-home terug", via: "Marc (screening)" },
        ],
        signalStrength: 88,
        trend: "up",
        contractReady: true,
        sources: ["job-type", "pulse"],
        kansFactors: [
          { label: "Vacature = Contract (ZZP/interim)", points: 40, source: "job-type" },
          { label: "Kandidaat in proces (take-home)", points: 30, source: "pulse" },
          { label: "Gesprek 3 dagen geleden", points: 18, source: "pulse" },
        ],
        nextOptions: [
          {
            id: "shortlist",
            label: "Shortlist sturen",
            desc: "Direct contractors voorstellen — rol is al contract",
          },
          {
            id: "interim-pitch",
            label: "Eerst kennismaken met HM",
            desc: "Kort bericht, daarna shortlist",
          },
          {
            id: "watch",
            label: "Alleen monitoren",
            desc: "Wachten tot Marc verder is",
          },
        ],
        suggestedNext: "shortlist",
        suggestedWho: "agent",
        status: "hot",
      },
      {
        id: "r3",
        company: "Bunq",
        hm: "EM Cloud",
        hmRole: "Engineering Manager",
        role: "Cloud Engineer interim",
        roleType: "interim / ZZP",
        employmentPosted: "Interim",
        lastTalk: "2026-07-28",
        lastTalkLabel: "9 dagen geleden",
        talks: [
          { when: "28 jul–5 aug", what: "3 pool-signalen ‘interim open’", via: "geaggregeerd" },
        ],
        signalStrength: 85,
        trend: "flat",
        contractReady: true,
        sources: ["job-type", "pulse"],
        kansFactors: [
          { label: "Vacature = Interim/ZZP", points: 40, source: "job-type" },
          { label: "3 kandidaten noemen Bunq interim", points: 30, source: "pulse" },
          { label: "Laatste signaal 9 dagen geleden (− freshness)", points: 15, source: "pulse" },
        ],
        nextOptions: [
          {
            id: "shortlist",
            label: "2 contractors voorstellen",
            desc: "Opvolging: al 9 dagen geen contact na interim-signaal",
          },
          {
            id: "interim-pitch",
            label: "Eerst checkbericht",
            desc: "Vragen of de rol nog open is",
          },
          {
            id: "watch",
            label: "Parkeren",
            desc: "Lage prioriteit deze week",
          },
        ],
        suggestedNext: "shortlist",
        suggestedWho: "self",
        status: "warm",
      },
      {
        id: "r4",
        company: "Adyen",
        hm: "Observability lead",
        hmRole: "Platform Engineering",
        role: "Sr Observability Infra",
        roleType: "extern onzeker",
        employmentPosted: "Full-time",
        lastTalk: "2026-08-04",
        lastTalkLabel: "2 dagen geleden",
        talks: [
          { when: "4 aug", what: "Recruiter screen (alleen vast)", via: "Priya" },
        ],
        signalStrength: 61,
        trend: "down",
        contractReady: false,
        sources: ["pulse"],
        kansFactors: [
          { label: "Gesprek 2 dagen geleden", points: 25, source: "pulse" },
          { label: "Alleen vast besproken (−)", points: 10, source: "pulse" },
          { label: "Geen 2e kandidaat-signaal", points: 15, source: "pulse" },
          { label: "Schaarste / seniority", points: 11, source: null },
        ],
        nextOptions: [
          {
            id: "watch",
            label: "Alleen monitoren",
            desc: "Nog geen harde ZZP-pitch — te veel perm-signalen",
          },
          {
            id: "interim-pitch",
            label: "Voorzichtige interim-check",
            desc: "Alleen als capaciteit knelt",
          },
          {
            id: "shortlist",
            label: "Shortlist klaarzetten",
            desc: "Intern klaarzetten, nog niet versturen",
          },
        ],
        suggestedNext: "watch",
        suggestedWho: "agent",
        status: "watch",
      },
      {
        id: "r5",
        company: "MessageBird / Bird",
        hm: "Onbekend",
        hmRole: "nog te resolven",
        role: "SRE / Cloud",
        roleType: "extern mogelijk",
        employmentPosted: "Full-time",
        lastTalk: null,
        lastTalkLabel: "geen gesprek bekend",
        talks: [],
        signalStrength: 34,
        trend: "flat",
        contractReady: false,
        sources: ["stale-job"],
        kansFactors: [
          { label: "Alleen job-alert, 40+ dagen open (zwak)", points: 20, source: "stale-job" },
          { label: "Hiring manager onbekend (−)", points: 5, source: null },
          { label: "Geen kandidaat-gesprek bekend", points: 9, source: "pulse" },
        ],
        nextOptions: [
          {
            id: "find-hm",
            label: "Hiring manager achterhalen",
            desc: "Via Pulse of LinkedIn — daarna pas outreach",
          },
          {
            id: "watch",
            label: "Alleen monitoren",
            desc: "Te weinig signaal voor actie",
          },
          {
            id: "interim-pitch",
            label: "Alvast conceptbericht",
            desc: "Pas versturen als HM bekend is",
          },
        ],
        suggestedNext: "find-hm",
        suggestedWho: "agent",
        status: "cold",
      },
    ],

    signalHow: [
      {
        title: "Sterkste: eigen kandidaatgesprekken",
        text: "Screening + Pulse: ‘waar interview je, met wie, wanneer, contract?’ → rij in dit dashboard. Jij bent de enige die dit live hoort.",
      },
      {
        title: "Cluster = bewijs",
        text: "2+ kandidaten noemen hetzelfde bedrijf/HM binnen 14 dagen → heat omhoog, ook zonder job-type Contract.",
      },
      {
        title: "Jouw eigen pipeline",
        text: "Als jij iemand hebt voorgesteld: interviewdata uit agenda/CRM is goud — ‘gesprek heeft plaatsgevonden’ weet je dan hard.",
      },
      {
        title: "Zwakker / aanvullend",
        text: "HM-posts, job reposts, RPS+ BD, Freelance.nl. Die zeggen ‘ze zoeken’, niet automatisch ‘er was een gesprek over een externe rol’.",
      },
    ],

    signals: [
      {
        id: "s1",
        label: "Explicit contract",
        weight: "hoog",
        how: "Job type Contract / Temporary, keywords ZZP, interim, freelance, contractor",
        inRps: "Ja — Jobs + filters; open-to-contract op kandidaten (niet op companies)",
      },
      {
        id: "s2",
        label: "Agency end-client",
        weight: "hoog",
        how: "Staffing-post noemt Adyen / eindklant + duur + tariefindicatie",
        inRps: "Deels — via Jobs/posts search in project",
      },
      {
        id: "s3",
        label: "Hiring velocity",
        weight: "midden",
        how: "Meerdere infra-roles open, reposts, HM posts (‘we're hiring’)",
        inRps: "Talent Insights + BD mode (RPS+)",
      },
      {
        id: "s4",
        label: "Time-open / scarce skills",
        weight: "midden",
        how: "Vacature lang open + schaarse stack → interim-pitch kans",
        inRps: "Indirect via Insights / project aging",
      },
      {
        id: "s5",
        label: "Perm-only blocker",
        weight: "negatief",
        how: "Office-first, relocation, ‘no remote’, geen contract-type",
        inRps: "Ja — lees employment type + tekst",
      },
    ],
    watchlist: [
      {
        id: "w1",
        company: "Adyen",
        role: "Infrastructure (Cloud) Engineer",
        source: "RPS project + HM LinkedIn post",
        employment: "Full-time",
        contractScore: 48,
        urgency: 82,
        why: [
          "Actieve HM-post + careers listing",
          "Schaarse Linux/multi-cloud skills",
          "Geen explicit ZZP/contract in tekst",
          "Office-first Amsterdam = perm-bias",
        ],
        nextAction: "HM benaderen: interim parallel aan perm-werving",
        status: "active",
      },
      {
        id: "w2",
        company: "Adyen",
        role: "Senior Observability Infrastructure Engineer",
        source: "Careers / job boards",
        employment: "Full-time",
        contractScore: 35,
        urgency: 70,
        why: [
          "10+ yr seniority · lastig te vullen",
          "Platform/K8s schaarste",
          "Sterke perm-signalen",
        ],
        nextAction: "Monitoren; alleen pitchen bij expliciete capaciteitsdruk",
        status: "watch",
      },
      {
        id: "w3",
        company: "Mollie",
        role: "Platform Engineer (via agency hint)",
        source: "RPS+ BD signal (mock)",
        employment: "Contract",
        contractScore: 88,
        urgency: 75,
        why: ["Job type Contract", "6 maanden genoemd", "ZZP in beschrijving"],
        nextAction: "Direct intake → delivery flow",
        status: "hot",
      },
      {
        id: "w4",
        company: "Bunq",
        role: "Cloud Engineer interim",
        source: "Freelance.nl + RPS keyword alert",
        employment: "Interim",
        contractScore: 91,
        urgency: 68,
        why: ["Explicit interim", "Einddatum in posting"],
        nextAction: "Opdracht aanmaken in Regie",
        status: "hot",
      },
    ],
    methods: [
      {
        title: "In RPS / RPS+",
        items: [
          "RPS-project per klant/HM — alerts op nieuwe jobs & posts",
          "RPS+ Business Development mode — companies die actief hiring zijn",
          "Talent Insights — hiring trends, headcount, skill demand per bedrijf",
          "Saved searches: Contract + ZZP + interim + company list (Adyen, …)",
        ],
      },
      {
        title: "Kandidaat als sensor (interview intel)",
        items: [
          "Bij elke screening 3 ‘waar speelt het nu?’-vragen",
          "Cluster antwoorden → hot companies / teams / stages",
          "Alleen gebruiken met toestemming; nooit naam doorspelen zonder ok",
          "Trigger: 2+ kandidaten noemen zelfde bedrijf → Demand alert",
        ],
      },
      {
        title: "Jobs → persoonlijke HM-outreach",
        items: [
          "Filter: Contract/ZZP/interim OF schaarse perm + urgency",
          "Resolve hiring manager / team lead (RPS, post author, careers)",
          "AI schrijft 1:1 bericht — jij keurt goed vóór send",
          "Pitch: wij leveren contractor parallel aan jullie werving",
        ],
      },
    ],

    /* Kandidaat-uitvraag → waar speelt het nu */
    intelQuestions: [
      "Waar interview je momenteel / waar zit je in proces?",
      "Welk bedrijf of team heeft nu écht haast (contract of perm)?",
      "Weten ze of interim/ZZP ook een optie is, of alleen vast?",
      "Wie is de hiring manager of het team (alleen als je mag delen)?",
    ],

    intelLeads: [
      {
        id: "i1",
        kandidaat: "Samira El Amrani",
        company: "Adyen",
        team: "Infrastructure / Cloud Foundations",
        stage: "2e gesprek · tech lead",
        when: "deze week",
        contractHint: "Posting = perm; HM noemde ‘capaciteit vóór Q4’",
        heat: 92,
        permission: "mag anoniem gedeeld",
        note: "Interview loopt nu — time-to-capacity argument sterk",
      },
      {
        id: "i2",
        kandidaat: "Marc de Vries",
        company: "Mollie",
        team: "Platform",
        stage: "take-home teruggekregen",
        when: "afgelopen 5 dagen",
        contractHint: "Expliciet contract 6 mnd in gesprek genoemd",
        heat: 88,
        permission: "mag bedrijf + rol delen",
        note: "Bevestigt hot lead Mollie Platform",
      },
      {
        id: "i3",
        kandidaat: "Priya Nair",
        company: "Adyen",
        team: "Observability Platform",
        stage: "recruiter screen gedaan",
        when: "gisteren",
        contractHint: "Alleen vast besproken",
        heat: 71,
        permission: "alleen geaggregeerd",
        note: "2e Adyen-signaal deze week → cluster alert",
      },
      {
        id: "i4",
        kandidaat: "Pool · Cloud AMS",
        company: "Bunq",
        team: "Cloud Eng",
        stage: "3 kandidaten noemen ‘interim open’",
        when: "laatste 10 dagen",
        contractHint: "ZZP expliciet",
        heat: 85,
        permission: "geaggregeerd uit 3 screens",
        note: "Geen namen — wel vraag-signaal",
      },
    ],

    /* Gefilterde jobs → klaarstaande HM-berichten */
    outreachFilter: {
      include: ["Contract", "Temporary", "ZZP", "interim", "freelance", "contractor"],
      softInclude: ["posted < 14d", "repost", "scarce skills", "HM post"],
      exclude: ["internship", "werkstudent"],
    },

    outreachQueue: [
      {
        id: "o1",
        company: "Adyen",
        role: "Infrastructure (Cloud) Engineer",
        channel: "LinkedIn",
        toName: "Victor Camargo",
        toRole: "Cloud Engineer · hiring post author",
        whyNow: "HM-post actief + 2 kandidaten in interview-proces deze week",
        status: "draft",
        subject: null,
        body: `Hoi Victor,

Ik zag jullie Infrastructure (Cloud) Engineer-posting in Amsterdam — Linux at scale, multi-cloud, Terraform/Pulumi.

Jullie werven vast; tegelijk horen we in de markt dat infra-capaciteit vóór Q4 knelt. Wij bemiddelen senior cloud/infra contractors (ZZP) die office-first in Amsterdam kunnen starten.

Als interim parallel aan permanente hiring nuttig is, stuur ik graag 1–2 pre-screened profielen (beschikbaarheid, tarief, hybrid/cloud depth al gecheckt).

Geen spam-lijst — alleen dit team, alleen als het helpt.

Groet,
Kevin`,
      },
      {
        id: "o2",
        company: "Mollie",
        role: "Platform Engineer",
        channel: "E-mail",
        toName: "Hiring Manager Platform",
        toRole: "via job posting",
        whyNow: "Job type Contract · kandidaat bevestigt 6 mnd in proces",
        status: "draft",
        subject: "Contractors voor Platform Engineer — pre-screened shortlist",
        body: `Beste,

Jullie Platform Engineer-opdracht (contract) kwam langs in onze RPS/job-monitor. Wij hebben ZZP’ers in Amsterdam met platform/cloud-diepte die deze week beschikbaar zijn voor een gesprek.

Ik kan binnen 24u een korte shortlist sturen (fit, tarief, startdatum) — zonder dat jullie opnieuw de hele markt hoeven te scannen.

Past dat? Dan plan ik het graag in.

Met vriendelijke groet,
Kevin · Regie`,
      },
      {
        id: "o3",
        company: "Bunq",
        role: "Cloud Engineer interim",
        channel: "LinkedIn",
        toName: "Engineering Manager Cloud",
        toRole: "team lead (mock resolve)",
        whyNow: "Explicit interim + 3 pool-signalen",
        status: "ready",
        subject: null,
        body: `Hoi,

Korte check: jullie Cloud Engineer interim staat open. Wij hebben 2 contractors die matchen op jullie stack en al weten dat Bunq interim draait.

Zal ik ze voorstellen, of is de shortlist al vol?

Kevin`,
      },
    ],
  },

  orchestratie: [
    { from: "Screening", to: "Demand", label: "interview intel" },
    { from: "Demand", to: "Sales", label: "HM outreach" },
    { from: "Demand", to: "Matching", label: "HM need" },
    { from: "Sourcing", to: "Screening", label: "top 20" },
    { from: "Screening", to: "Matching", label: "qualified" },
    { from: "Matching", to: "Sales", label: "score ≥80" },
    { from: "Sales", to: "CRM", label: "voorgesteld" },
    { from: "Market", to: "Demand", label: "tarieven" },
  ],

  activityPool: [
    { agent: "Demand", text: "Interview intel: Samira in 2e ronde Adyen Infra — heat 92" },
    { agent: "Demand", text: "Cluster: 2× Adyen genoemd in screens deze week" },
    { agent: "Demand", text: "Outreach draft klaar → Victor Camargo (Adyen Cloud)" },
    { agent: "Screening", text: "Intel-vragen gesteld aan Marc · Mollie contract bevestigd" },
    { agent: "Sales", text: "HM-mail Mollie Platform klaargezet ter review" },
    { agent: "Sourcing", text: "RPS project sync: 14 nieuwe cloud-infra profielen Amsterdam" },
    { agent: "Matching", text: "Matchscore Samira ↔ Adyen Infra: 91%" },
    { agent: "Market", text: "Cloud infra AMS mediaan €112/uur (+3%)" },
    { agent: "Demand", text: "Job filter: 3 contract/interim hits → outreach queue" },
    { agent: "CRM", text: "Bunq outreach gemarkeerd als ready to send" },
  ],

  steps: [
    {
      id: 1,
      label: "Intake",
      agent: "Matching",
      agentId: "matching",
      title: "Intake · wat zoekt Adyen?",
      body: "Agent vat de klantvraag samen. Jij bevestigt: dit is de opdracht waar we interim op gaan pitchen.",
      agentDid: "Samengevat: must-haves, locatie, tariefband, perm-posting + interim-hoek.",
      approveWhat: "Klopt deze intake? Mag sourcing starten op deze scope?",
      view: "intake",
      tradMin: 45,
      aiMin: 4,
    },
    {
      id: 2,
      label: "Sourcing",
      agent: "Sourcing",
      agentId: "sourcing",
      title: "Sourcing · shortlist klaar",
      body: "Agent zocht open-to-contract infra/cloud in AMS. Samira #1, Marc en Priya als backup.",
      agentDid: "3 kandidaten gerankt op match + beschikbaarheid + tarief.",
      approveWhat: "Akkoord dat Samira de lead is (en Marc/Priya backup)? Of wil je iemand anders voorop?",
      view: "sourcing",
      tradMin: 180,
      aiMin: 15,
    },
    {
      id: 3,
      label: "Screening",
      agent: "Screening",
      agentId: "screening",
      title: "Screening · Samira gecheckt",
      body: "Screening Agent vroeg Samira: start, tarief, ZZP, Terraform/hybrid, office-dagen.",
      agentDid: "Chat afgerond: start 1 sep, €118, BV/ZZP oké, 3–4 dagen AMS.",
      approveWhat: "Samira mag door naar CV-analyse / voorstel? Geen deal-breakers gemist?",
      view: "screening",
      tradMin: 90,
      aiMin: 12,
    },
    {
      id: 4,
      label: "CV-analyse",
      agent: "Matching",
      agentId: "matching",
      title: "CV-analyse · match 91%",
      body: "Matching Agent scoort Samira tegen Adyen must-haves en markeert risico’s.",
      agentDid: "Score 91%. Risico: geen Adyen/payments; wel regulated fintech.",
      approveWhat: "Akkoord met dit matchbeeld? Mag Sales een voorstel-concept schrijven?",
      view: "match",
      tradMin: 40,
      aiMin: 3,
    },
    {
      id: 5,
      label: "Voorstel",
      agent: "Sales",
      agentId: "sales",
      title: "Voorstel · bericht naar Adyen",
      body: "Sales Agent schreef een interim-pitch: Samira naast (of vooruitlopend op) FTE-werving.",
      agentDid: "Conceptmail klaar — toon, tarief, availability, interim-angle.",
      approveWhat: "Mag dit bericht namens Brand New Start naar de hiring manager?",
      view: "voorstel",
      tradMin: 25,
      aiMin: 2,
    },
    {
      id: 6,
      label: "Planning",
      agent: "CRM",
      agentId: "crm",
      title: "Planning · interviews",
      body: "CRM Agent stelt slots voor met Cloud HM, infra lead en architect.",
      agentDid: "3 voorgestelde slots in de agenda van Adyen-contacten.",
      approveWhat: "Akkoord met deze interview-slots? Of pas je tijden aan?",
      view: "planning",
      tradMin: 35,
      aiMin: 5,
    },
    {
      id: 7,
      label: "Follow-up",
      agent: "CRM",
      agentId: "crm",
      title: "Follow-up · pool warm",
      body: "Zolang Adyen openstaat: backups (Marc/Priya) en pool warm houden.",
      agentDid: "Reminders gezet voor Marc, Priya en de Cloud Infra AMS-pool.",
      approveWhat: "Akkoord met deze follow-up-acties? Of wil je zelf iemand bellen?",
      view: "followup",
      tradMin: 60,
      aiMin: 8,
    },
    {
      id: 8,
      label: "Admin",
      agent: "Market+",
      agentId: "market",
      title: "Admin · als deal rond is",
      body: "Na een ja: DBA/overeenkomst, security onboarding Adyen, uren, verlenging.",
      agentDid: "Checklist klaargezet (nog niet uitgevoerd — wacht op deal).",
      approveWhat: "Checklist oké om te starten zodra Adyen groen licht geeft?",
      view: "admin",
      tradMin: 50,
      aiMin: 10,
    },
  ],

  agents: [
    { id: "demand", name: "Demand Agent", role: "Zoekt contracting-signalen & radar", status: "actief" },
    { id: "sourcing", name: "Sourcing Agent", role: "Zoekt en rankt kandidaten", status: "actief" },
    { id: "screening", name: "Screening Agent", role: "Eerste vragen (tarief, ZZP, start)", status: "idle" },
    { id: "matching", name: "Matching Agent", role: "Matchscore kandidaat ↔ opdracht", status: "actief" },
    { id: "sales", name: "Sales Agent", role: "Schrijft voorstellen & HM-berichten", status: "idle" },
    { id: "crm", name: "CRM Agent", role: "Planning, follow-up, warm houden", status: "actief" },
    { id: "market", name: "Market Agent", role: "Tarieven & schaarste", status: "actief" },
  ],

  /* Slimme bronnen om open contracting-kansen te vinden (Pulse is er één van) */
  intel: {
    intro:
      "Elke bron is een plek waar Demand Agent (of jullie netwerk) een signaal oppikt. Meer bronnen op één bedrijf = sterkere kans op de radar.",
    sources: [
      {
        id: "tender",
        title: "Aanbesteding gewonnen",
        fetchFrom: "TenderNed · TED (EU) · award notices",
        why: "Ze hebben de klus binnen — nu moeten ze capaciteit vullen. Vaak te laat voor FTE.",
        how: "Filter IT/digital awards → match stack + regio → radarrij met hoge score.",
        agent: "Demand Agent",
        strength: "zeer sterk",
        example: "Fintech AMS wint €4,2M cloud-migratie → 3–6 mnd infra-surge",
      },
      {
        id: "pulse",
        title: "Pulse & screening",
        fetchFrom: "Pulse-formulier · Screening Agent in gesprekken",
        why: "Kandidaten vertellen waar ze interviewen. Cluster = hard bewijs dat er iets speelt.",
        how: "Vragen: bedrijf, fase, ZZP besproken? → gesprek gemeld + kanspunten.",
        agent: "Screening + Demand",
        strength: "sterk (als volume)",
        example: "2 kandidaten melden Adyen-gesprek dezelfde week",
      },
      {
        id: "hm-post",
        title: "Hiring manager posts",
        fetchFrom: "LinkedIn · X · HM-profielen in target-accounts",
        why: "HM vraagt zelf om capacity / interim / ZZP — directe buying intent.",
        how: "Monitor keywords: interim, contractor, ZZP, ASAP capacity.",
        agent: "Demand Agent",
        strength: "sterk",
        example: "Cloud lead: ‘temporary AWS capacity this quarter’",
      },
      {
        id: "job-type",
        title: "Vacature = contract / interim",
        fetchFrom: "LinkedIn Jobs · careers pages · Freelance.nl · RPS",
        why: "Rol staat al als Contract/Interim/ZZP — geen overtuigingswerk over het type.",
        how: "Employment-type filter + alert als een FTE-rol omslaat naar contract.",
        agent: "Demand Agent",
        strength: "zeer sterk",
        example: "Mollie Platform Engineer gepost als Contract",
      },
      {
        id: "stale-job",
        title: "Vacature die blijft hangen",
        fetchFrom: "Job boards · careers pages (first-seen + reposts)",
        why: "Lang open + urgente wording = FTE lukt niet → interim-pitch moment.",
        how: "Track dagen-open, repost-count, taal als urgent/ASAP.",
        agent: "Demand + Market",
        strength: "middel–sterk",
        example: "SRE 71 dagen open, 2× gerepost",
      },
      {
        id: "compliance",
        title: "Compliance-deadline",
        fetchFrom: "Risk filings · regulatory kalenders · security-job spikes",
        why: "DORA/NIS2/audit: project moet af, headcount mag vaak niet omhoog.",
        how: "Deadline + gerelateerde vacatures → timing-boost op kans.",
        agent: "Demand Agent",
        strength: "sterk (timing)",
        example: "Bank noemt DORA Q4 + 2 security roles",
      },
      {
        id: "agency-swarm",
        title: "Bureau-zwerm",
        fetchFrom: "Freelance.nl · LinkedIn jobs · agency feeds",
        why: "Meerdere bureaus posten dezelfde rol = klant zoekt hard.",
        how: "Dedup per bedrijf+rol; 3+ agencies = boost.",
        agent: "Demand Agent",
        strength: "middel",
        example: "4 bureaus posten Java interim bijzelfde insurer",
      },
      {
        id: "warm-alumni",
        title: "Ex-plaatsingen & netwerk",
        fetchFrom: "Eigen CRM · LinkedIn van ex-contractors",
        why: "Iemand die jullie plaatsten kent de hiring pain van binnen.",
        how: "Nieuwe werkgever van alumni → warm intro-pad.",
        agent: "CRM + Demand",
        strength: "zeer sterk (relatie)",
        example: "Ex-plaatsing nu EM — open voor intro",
      },
      {
        id: "funding-freeze",
        title: "Funding + FTE-freeze",
        fetchFrom: "Funding news · earnings · LinkedIn hiring-taal",
        why: "Budget voor projecten, stop op vaste headcount → contractor window.",
        how: "Koppel funding/freeze aan open projecttaal op careers.",
        agent: "Market + Demand",
        strength: "middel–sterk",
        example: "Series B + ‘careful on permanent hires’",
      },
      {
        id: "kickoff",
        title: "Project kick-off publiek",
        fetchFrom: "LinkedIn · meetup/talks · blogposts",
        why: "Migratie/rebuild aangekondigd → capaciteitsgat volgt.",
        how: "Keywords kickoff/migration/rebuild + company graph.",
        agent: "Demand Agent",
        strength: "middel",
        example: "Architect: hybrid-cloud program next month",
      },
      {
        id: "backfill",
        title: "Contractor backfill",
        fetchFrom: "CRM einddata · LinkedIn open-to-work ex-ZZP’ers",
        why: "Contract loopt af of ZZP stopt → direct gat op dezelfde stoel.",
        how: "End-date tracking + exit-signalen.",
        agent: "CRM Agent",
        strength: "sterk",
        example: "Infra ZZP eindigt 1 sep bij betalingsprovider",
      },
    ],
    feed: [
      {
        when: "12 min",
        source: "tender",
        company: "Zorgverzekeraar Noord",
        signal: "TenderNed: cloud-transformatie gegund (€3,1M) — oplevering 9 mnd",
        score: 92,
        action: "Interim-pitch Platform/Infra",
      },
      {
        when: "1 u",
        source: "hm-post",
        company: "Adyen",
        signal: "HM LinkedIn: ‘temporary AWS capacity this quarter’",
        score: 88,
        action: "Shortlist + bericht",
      },
      {
        when: "3 u",
        source: "pulse",
        company: "Booking.com",
        signal: "2 Pulse-meldingen: tech-ronde Platform Engineer",
        score: 81,
        action: "Radar hot + monitor ZZP",
      },
      {
        when: "5 u",
        source: "agency-swarm",
        company: "NN Group",
        signal: "3 bureaus posten Java interim AMS dezelfde week",
        score: 72,
        action: "Monitor + warm intro check",
      },
      {
        when: "gisteren",
        source: "compliance",
        company: "Retail bank AMS",
        signal: "DORA Q4 genoemd in risk update + 2 security vacatures",
        score: 79,
        action: "Security contractor longlist",
      },
      {
        when: "gisteren",
        source: "stale-job",
        company: "Mollie",
        signal: "SRE vacature 71 dagen open, 2× gerepost, ‘urgent’",
        score: 74,
        action: "Interim-pitch naast FTE",
      },
      {
        when: "gisteren",
        source: "backfill",
        company: "Bunq",
        signal: "Infra ZZP eindigt 1 sep — stoel komt vrij",
        score: 84,
        action: "Backfill shortlist klaarzetten",
      },
      {
        when: "2 d",
        source: "warm-alumni",
        company: "Scale-up FinOps",
        signal: "Ex-plaatsing nu Engineering Manager — open voor intro",
        score: 90,
        action: "Warm belletje BNS",
      },
      {
        when: "2 d",
        source: "job-type",
        company: "Coolblue",
        signal: "Platform Engineer gepost als Contract (6 mnd)",
        score: 86,
        action: "Direct shortlist",
      },
      {
        when: "3 d",
        source: "funding-freeze",
        company: "Fintech Series B",
        signal: "Funding + ‘careful on permanent hires’ in LinkedIn-post",
        score: 70,
        action: "Interim-angle voorbereiden",
      },
      {
        when: "3 d",
        source: "kickoff",
        company: "ING Tech",
        signal: "Architect post: hybrid-cloud program kickoff next month",
        score: 68,
        action: "Radar watch + HM resolven",
      },
      {
        when: "4 d",
        source: "pulse",
        company: "MessageBird / Bird",
        signal: "1 Pulse: recruiter screen SRE — ZZP niet besproken",
        score: 55,
        action: "Licht monitoren",
      },
    ],
  },

  proces: [
    {
      id: "p1",
      num: "1",
      title: "Signalen binnen",
      short: "Agents scannen bronnen · BNS deelt Pulse",
      happens:
        "Demand Agent scant aanbestedingen, HM-posts, hangende vacatures en compliance-deadlines. Screening/Pulse vangt kandidatengesprekken. Samen vullen ze de radar.",
      bns: "Jullie activeren het netwerk (Pulse delen, warme intros) — agents doen het scannen.",
      agents: ["Demand Agent", "Screening Agent", "Market Agent"],
      agentJobs: [
        { agent: "Demand Agent", does: "Scant TenderNed/TED, HM-posts, stale jobs, compliance-kalenders" },
        { agent: "Screening Agent", does: "Vraagt in gesprekken: waar interview je, ZZP besproken?" },
        { agent: "Market Agent", does: "Koppelt schaarste & tariefband aan elk signaal" },
      ],
      bnsJobs: [
        "Deelt Pulse met kandidaten (relatie, niet spam)",
        "Geeft warme intros / ex-plaatsingen door",
        "Zet target-accounts aan of uit",
      ],
      human: "Licht: netwerk activeren. Geen handmatig scrapen.",
      humanLevel: "licht",
    },
    {
      id: "p2",
      num: "2",
      title: "Radar",
      short: "Agents ordenen · BNS scant hot",
      happens:
        "Demand Agent zet per bedrijf: hiring manager, bronnen, kans-score, ZZP-signaal. Jij ziet alleen wat ertoe doet.",
      bns: "Jullie kijken wáár jullie willen zitten — niet zélf de markt uitpluizen.",
      agents: ["Demand Agent", "Market Agent"],
      agentJobs: [
        { agent: "Demand Agent", does: "Bouwt/updateert radarrij per bedrijf + score-opbouw" },
        { agent: "Market Agent", does: "Voegt schaarste, bandbreedte tarief, timing toe" },
      ],
      bnsJobs: [
        "Scant hot / filters",
        "Klikt bedrijven open die jullie kennen",
        "Negeert noise (agent blijft monitoren)",
      ],
      human: "Licht: prioriteren met oog en klantkennis.",
      humanLevel: "licht",
    },
    {
      id: "p3",
      num: "3",
      title: "Kies actie",
      short: "Geen agent beslist — jij wel",
      happens:
        "Geen agent mag zelf outreach of plaatsing starten. Brand New Start kiest kwalificatie (interim, shortlist, monitor…) én of een agent mag uitvoeren of jij het zelf doet.",
      bns: "Dit is jullie regie-moment. Agents wachten op ‘Start’.",
      agents: [],
      agentJobs: [],
      bnsJobs: [
        "Kiest volgende stap (kwalificatie)",
        "Kiest: agent uitvoeren óf zelf",
        "Drukt Start — pas dan mag AI door",
      ],
      human: "Zwaar: strategische beslissing + verantwoordelijkheid naar de klant.",
      humanLevel: "zwaar",
    },
    {
      id: "p4a",
      num: "4a",
      title: "Outreach",
      short: "Agent schrijft · BNS keurt toon",
      happens:
        "Sales Agent schrijft een conceptbericht op basis van het signaal. Brand New Start keurt goed of herschrijft — het gaat uit náám van jullie relatie.",
      bns: "Klantrelatie en toon zijn van Brand New Start. Agent levert snelheid, niet de stem.",
      agents: ["Sales Agent", "Demand Agent"],
      agentJobs: [
        { agent: "Sales Agent", does: "Schrijft concept-HM-bericht + onderwerpregel" },
        { agent: "Demand Agent", does: "Stopt why-now feiten in het concept (bron + timing)" },
      ],
      bnsJobs: [
        "Leest & past toon aan",
        "Keurt goed / Ready / Verzonden",
        "Belt na als de relatie dat vraagt",
      ],
      human: "Keurt goed: relatie en toon blijven menselijk.",
      humanLevel: "middel",
      branch: true,
    },
    {
      id: "p4b",
      num: "4b",
      title: "Opdracht",
      short: "Agents leveren stappen · BNS keurt elke poort",
      happens:
        "Bij een lopende klantvraag: Matching vat samen → Sourcing rankt → Screening filtert → Sales schrijft voorstel → CRM plant. Elke stap wacht op jullie goedkeuring.",
      bns: "Jullie zijn de poortwachter én closer. Agents doen het uitvoerende werk tussen de poorten.",
      agents: ["Matching Agent", "Sourcing Agent", "Screening Agent", "Sales Agent", "CRM Agent"],
      agentJobs: [
        { agent: "Matching Agent", does: "Must-haves + matchscore + risico’s" },
        { agent: "Sourcing Agent", does: "Zoekt/rankt open-to-contract kandidaten" },
        { agent: "Screening Agent", does: "Tarief, ZZP, start, deal-breakers" },
        { agent: "Sales Agent", does: "Interim-voorstel-concept" },
        { agent: "CRM Agent", does: "Interviewslots + follow-up reminders" },
      ],
      bnsJobs: [
        "Goedkeuren of overrulen per stap",
        "Onderhandelt tarief & teamfit",
        "Doet closing met hiring manager",
      ],
      human: "Keurt goed per poort; soft skills en deal = BNS.",
      humanLevel: "middel",
      branch: true,
    },
    {
      id: "p5",
      num: "5",
      title: "BNS regisseert",
      short: "Agents monitoren · BNS onderhandelt",
      happens:
        "Agents houden radar en pool warm. Brand New Start grijpt in bij tarief, deal-breakers, teamfit en alles wat vertrouwen raakt.",
      bns: "Onderscheidend vermogen: relatie, onderhandeling, schaarse kandidaten overtuigen.",
      agents: ["Demand Agent", "CRM Agent", "Market Agent"],
      agentJobs: [
        { agent: "Demand Agent", does: "Blijft nieuwe signalen op radar zetten" },
        { agent: "CRM Agent", does: "Warm houden pool + follow-ups" },
        { agent: "Market Agent", does: "Signaleert tariefverschuivingen" },
      ],
      bnsJobs: [
        "Onderhandelt & sluit",
        "Bewaakt klantrelatie",
        "Beslist bij uitzonderingen",
      ],
      human: "Zwaar menselijk: acquisitie, relatie, closing.",
      humanLevel: "zwaar",
      end: true,
    },
  ],
};
